---
# tasks file for roles/nginx
- name: instalar nginx
  apt: name=nginx state=present
- name: copiar ficheros
  copy: src={{ item.value.nginxconf }} dest=/etc/nginx/sites-enabled/
  with_dict: '{{ nginx_conf }}'

  notify: reiniciar nginx
