apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  wp-config.php: |
    <?php

    define('DB_NAME', getenv('wordpress'));

    define('DB_USER', getenv('wordpressuser'));

    define('DB_PASSWORD', getenv('wordpress'));

    define('DB_HOST', getenv('mysql-svc'));

    define( 'DB_CHARSET', 'utf8' );

    define( 'DB_COLLATE', '' );

    define( 'AUTH_KEY',         'put your unique phrase here' );
    define( 'SECURE_AUTH_KEY',  'put your unique phrase here' );
    define( 'LOGGED_IN_KEY',    'put your unique phrase here' );
    define( 'NONCE_KEY',        'put your unique phrase here' );
    define( 'AUTH_SALT',        'put your unique phrase here' );
    define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );
    define( 'LOGGED_IN_SALT',   'put your unique phrase here' );
    define( 'NONCE_SALT',       'put your unique phrase here' );

    $table_prefix = 'wp_';

    define( 'WP_DEBUG', false );

    require_once( ABSPATH . 'wp-settings.php' );