apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: wordpress
spec:
  volumeMode: Filesystem
  storageClassName: mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-pvc
  labels:
    app: wordpress
spec:
  volumeMode: Filesystem
  storageClassName: files
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi