kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-ficheros
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: claim-mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G