node ('pi') {
    stage("inicio") {
        slackSend color: '#BADA55', message: 'Inicio pipeline K3S', channel: "#jenkins"
    }

   stage("test") {
        docker.image('python:latest').inside('-u root --privileged') { 
            checkout scm
            sh 'pip install virtualenv'
            sh 'virtualenv venv'
            sh 'source venv/bin/activate'
            sh 'pip install -r requirements.txt'
            sh 'python -m pytest -v tests/test_generator.py'
        
        }
    }

    stage("build") {
        docker.withRegistry('https://registry.gitlab.com', 'k3s_registry') {
            def customImage = docker.build("$registry:${env.BUILD_ID}")
            customImage.push("${env.BUILD_ID}")
            customImage.push("latest")
        }

    }

    stage("deploy") {
        sh "kubectl apply -f deploy/."
    }

    stage("final") {
        slackSend color: '#BADA55', message: 'Final pipeline K3S', channel: "#jenkins"
    }
    
}
