---
# tasks file for roles/wordpress
- name: descargar wordpress
  unarchive: 
    src: https://wordpress.org/latest.tar.gz
    dest: /root/
    remote_src: yes

- name: mover carpeta wordpress
  shell: "rsync -avz /root/wordpress/ /var/www/{{ dominio }}/"

- name: copiar wp-config
  template: src=wp-config.j2 dest=/var/www/{{ dominio }}/wp-config.php

- name: eliminar descarga wordpress
  shell: "rm /root/latest.tar.gz"

- name: eliminar carpeta wordpress
  shell: "rm -rf /root/wordpress"
  

- name: cambiar permisos wordpress
  shell: "chown -R www-data.www-data /var/www/{{ dominio }}/"
  

  